name: Artifact

on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: create fles
              run : |
                mkdir build
                echo "This is test build!!" > build/info.txt

            - name: upload the build folder    
              uses: action/upload-artifact@v7
              with:
                name: build-output
                path: build/

    job2:
        runs-on: ubuntu-latest
        steps:
            - name: download the build folder    
              uses: action/download-artifact@v8
              with:
                name: build-output
                path: ./build
              
            - name: display the build folder
              run: |
               ls -lart ./build
               cat ./build/info.txt
