name: CI

on:
    workflow_dispatch

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Install node js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install dependencies
              run: npm ci  

            - name: start the app
              run: npm start &

            - name: Wait for the application to boot
              run: sleep 5

            - name: Check Health
              run: exit 1
