name: matrix-build

on: 
   workflow_dispatch:
       
jobs:
    job1:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18, 20, 22]
        steps:
          - name: install Node
            uses: action/setup-node@v4
            with:
                node-version: ${{ matrix.node-version }}