name: matrix-build

on: 
   workflow_dispatch:
       
jobs:
    job1:
        runs-on: ubuntu-latest

        strategy: # to run the same job multiple times with different configurations, we can use matrix strategy
            matrix:
                node-version: [18, 20, 22]
        steps:
          - name: install Node
            uses: actions/setup-node@v4
            with:
                node-version: ${{ matrix.node-version }}