name : Variables

on: 
    workflow_dispatch:
        inputs:
            environment:
                description: 'Run environment'
                required: true
                default: 'test'
                type: choice
                options:
                    - dev
                    - prod
                    - test

            version:
               description: 'Application version'
               required: true
               default: '1.0.0'

env:
    GLOBAL_ENV: '1 Tire App'
jobs:
    job1:
       runs-on: ubuntu-latest
       env:
           JOB1_ENV: '1 Tire App'
       steps:
            - name: display Inputs
              run: |
                echo "Environment: ${{ inputs.environment }}"
                echo "App Version: ${{ inputs.version }}"

            - name: Global Environment Variables
              run: |
                echo "Environment: GLOBAL_ENV"  

            - name: Job1 Environment Variables
              run: |
                echo "Environment: JOB1_ENV"      

    job2:
       runs-on: ubuntu-latest
       env:
           JOB2_ENV: 'Monolithic'
       steps:
            - name: Job2 Environment Variables
              run: |
                echo "Environment: JOB2_ENV "

    
    job3:
       runs-on: ubuntu-latest
       env:
           JOB2_ENV: 'Monolithic'
       steps:
            - name: Print Repo Secrete and Variables
              run: |
                echo "Github Repo Secrete: ${{secrets.SECRETE_KEY_DEVOPS_JUNE_2026}} " 
                echo "Github Repo Variable: ${{vars.SOME_VARIABLE_DEVOPS_JUNE_2026}} "            